import { Task } from "@prisma/client";
import { type NextPage } from "next";
import Head from "next/head";
import { useEffect, useState } from "react";
import TodoModal from "../components/TodoModal";
import { HiX } from "react-icons/hi";

import { trpc } from "../utils/trpc";

const Home: NextPage = () => {
  const [todos, setTodos] = useState<Task[]>([]);
  const [todoModalOpen, setTodoModalOpen] = useState<boolean>(false);

  const { data: tasks, isLoading, isError } = trpc.task.getAll.useQuery();
  const { mutate: deleteTask } = trpc.task.deleteTask.useMutation({
    onSuccess(task) {
      setTodos((prev) => prev.filter((todo) => todo.id !== task.id));
    },
  });

  useEffect(() => {
    if (!isError && tasks) setTodos(tasks);
  }, [isError, tasks]);

  const handleModalOpen = () => {
    setTodoModalOpen(true);
  };

  if (!tasks || isLoading) return <p>Loading...</p>;

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      {todoModalOpen ? (
        <TodoModal setTodoModalOpen={setTodoModalOpen} setTodos={setTodos} />
      ) : null}

      <main className="mx-auto my-12 max-w-3xl">
        <div className="flex justify-between">
          <h2 className="text-2xl font-semibold">My Todo List</h2>
          <button
            onClick={handleModalOpen}
            className="rounded-xl bg-violet-500 p-2 text-sm text-white transition hover:bg-violet-600"
          >
            Add task
          </button>
        </div>

        <ul className="mt-4">
          {todos.map((task) => {
            const { id, name } = task;
            return (
              <li key={id} className="flex items-center justify-between">
                <span>{name}</span>
                <HiX
                  onClick={() => deleteTask({ id })}
                  className="text-lg text-red-500"
                />
              </li>
            );
          })}
        </ul>
      </main>
    </>
  );
};

export default Home;
